### PR TITLE
Issue 179 - Allow Users to hide NB sidebar (toggle)

### PR DESCRIPTION
**Pull request by alizeeschoen**
Added functionality to be able to hide the NB side bar. I changed the logout logo and used the 3 bars as a way button to hide the sidebar. I looked up a little around what other websites do for hiding side bars and the 3 bars logo seemed popular. I could also revert that and just have a hide-show button. 

Side bar shown: 
image

Side bar hidden: 
image

### CODE REVIEW

**Review by JumanaFM — CHANGES_REQUESTED** [review]
Great first commit! Thank you, Alizee! the code looks clean.  I have few comments:

1- can you please change the icon (burger icon) to something more intuitive that changes depending on the status (e.g. arrow pointing in and out for toggled sidebar)

2- When a highlight is clicked (activated) the sidebar should appear.

3- When the sidebar collapses on HTML pages (and PDFs) it leaves a space (see below) can you please handle that space. Experiment with different ways and share with me screenshots if you want before committing.
image

image

4- can you please experiment with other ways to hide the bar? For example the image below, on the right side of the page, you'll notice a "<" sign. That's the hypothesis sidebar collapsed. Can we have something similar for NB when collapsed?
image

**Comment by JumanaFM** [comment]
@alizeeschoen see comment above

**Comment by alizeeschoen** [comment]
@JumanaFM @karger 

I updated the code to have the hide/show highlights button: 
image
image

And I have addressed all the comments in here https://github.com/haystack/nbclient/pull/27#pullrequestreview-774488727

**Comment by alizeeschoen** [comment]
@JumanaFM Just added this feature, it reloads when trying to hide the HTML link

**Comment by JumanaFM** [comment]
Hi @alizeeschoen 
When I tested this PR this is what I get
image

and for PDF
image

**Comment by JumanaFM** [comment]
I noticed that when I hide the sidebar on HTML pages it just disappears. Is this the behavior you have in mind? What you proposed is nice in which a toggle appears on the side. 
Can you please create a new PR fixing those issues?

**Comment by alizeeschoen** [comment]
@JumanaFM I thought you asked for the sidebar to completely disappear when on an html page? (see below) Do you want me to have the toggle appear just like the PDF?

> @alizeeschoen
> The page should look like its original state when nb sidebar is hidden. like this
> image

**Pull request merged**
